name: FIFA DATA UPDATE

on:
    schedule:
        - cron: '0 4 * * *'
    
    workflow_dispatch:


jobs:
    update-data:
        runs-on: ubuntu-latest

        steps:
            - name: Set up Python
              uses: actions/setup-python@v5
              with:
                python-version: '3.12'
            
            - name: Install packages
              run: pip install requests pandas

            - name: Checkout repository
              uses: actions/checkout@v3
            
            - name: Import Data
              run: python scraping.py
            
            - name: Commit results
              run: |
                git config --local user.email "actions@github.com"
                git config --local user.name "GitHub Actions"
                git add data/wc2026_efi.csv
                git commit -m 'Data updated' || echo "No changes to commit"
                git push origin || echo "No changes to commit"

            
